version: '3.3'

services:
  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=posts
    ports:
      - 5432:5432

volumes:
  postgres_data: