version: '3.3'

services:
  web:
    container_name: "app"
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    command:
      - bash
      - -c
      - |
        while !</dev/tcp/postgresql/5432; do sleep 1; done;
        while !</dev/tcp/elasticsearch/9200; do sleep 1; done;
        uvicorn main:app --host 0.0.0.0 --reload
    networks:
      - modsen
    depends_on:
      - postgresql

  postgresql:
    container_name: "postgresql"
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - modsen

  elasticsearch:
    container_name: "elasticsearch"
    image: elasticsearch:8.8.0
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - modsen

volumes:
  postgres_data:
  elastic_data:

networks:
  modsen:
    driver: bridge